name: Build and deploy Spring Boot Application
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Deploying my own Spring Boot App
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Build the application
        run: mvn clean install

