name: Build and deploy Spring Boot Application
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Deploying my own Spring Boot App
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Build the application
        run: mvn clean install

      - name: Build Docker Image
        uses: docker/mapstruct-demo@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-cicd:$(date-'%d-%m-%Y%H-%M-%S')

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/mapstruct-demo@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-cicd:$(date-'%d-%m-%Y%H-%M-%S')


