name: Build and deploy Spring Boot Application
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Deploying my own Spring Boot App
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Build the application
        run: mvn clean install

      - name: Get current date # get the date of the build
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y--%H-%M-%S')"

      - name: Build the Docker image # push The image to the docker hub
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-cicd:${{ steps.date.outputs.date }}

#      - name: Build Docker Image
#        uses: docker/build-push-actions@v2
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: false
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-cicd:$(date-'%d-%m-%Y%H-%M-%S')
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-cicd:{{ steps.date.outputs.date }}


